# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do

	def prepare_version(options)
    increment_version_number(
        version_number: options[:version]
    )
 
    increment_build_number(
        build_number: options[:build]
    )
	end

 	desc "Description of what the lane does"
 	lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  	end

  	desc "打包上传到 Fir"
	lane :fir do |options|
		#sigh(adhoc:true)  #如果要使用ad-hoc打包, 则需打开此项配置
		gym(scheme: options[:scheme],
		# workspace: "xxx.xcworkspace", # 可省略
		configuration: "Debug",              # Debug or Release
		archive_path: options[:archive_path],
		clean: true,                           #清空上次打包信息
		output_directory: options[:outPath],
		output_name: options[:ipa_name],
		export_method:"development"                 # app-store, ad-hoc, package, enterprise, development, developer-id
		)	
		#使用自动证书管理
		# enable_automatic_code_signing(path: "HUIpaTest.xcodeproj")
		# 蒲公英自动上传
		# pgyer(api_key: "xxx", user_key: "xxx", password: "xxx", install_type: "2")
	end

end
